### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by sarankup** [totaljs/modules#25]
Hi,

In the definitions/modules.js, I see the below code
INSTALL('module','http://modules.totaljs.com/session/v1.00/session.js');

I have downloaded the session.js and saved under 
modules/session.js, ie., I want to load the session from my own hosting path. When I start the totaljs application using debug.js, I see the below error,

======= 2015-03-25 20:07:29: framework.install('module', 'undefined') ---> Refer
enceError: session is not defined ReferenceError: session is not defined

Please advise how to fix this.

**Comment by petersirka** [comment]
Hi @sarankup,
can you send me a whole example on my e-mail? petersirkaATgmailDOTcom.

Thanks.

**Comment by sarankup** [comment]
Hi @petersirka, Could you please brief the "whole example"?

**Comment by petersirka** [comment]
I want to see your code, nothing more :-)

**Comment by sarankup** [comment]
Hi @petersirka,

Sorry for not responding sooner. I am not sure what went wrong. But now, modules/session.js,  it works well. Thanks again.

**Comment by petersirka** [comment]
Thanks :+1:
