### ISSUE TITLE
auth whether already logged

### ISSUE THREAD

**Issue by sarankup** [totaljs/modules#33]
Hi,

I am referring the below page and I use it.
https://github.com/totaljs/modules/blob/master/Security/auth/example/controllers/default.js

When I click the json_logoff function second time, then the page response is "401: Unauthorized". In the below code, I can I check whether the user already logoff, so I can re-route to some other page.

```
function json_logoff() {
    var self = this;
    var auth = MODULE('auth');
    var user = self.user;
    auth.logoff(self, user.id);
    self.redirect('/');
}
```

**Comment by matusszabo** [comment]
Hi,
route "logoff" has flag "authorize", so this is correct behaviour, please read the documentation (Usage in controllers): http://docs.totaljs.com/v1.8.x/en.html#pages~Authorization

Thank you
