### ISSUE TITLE
Social Login Oauth

### ISSUE THREAD

**Issue by sarankup** [totaljs/modules#34]
Hi,

I am referring the page https://github.com/totaljs/modules/tree/master/Security/oauth2,

In which everything works well except the Github. When I click the Github it take me to the Twitter API. I think, my code is correct.

**Comment by petersirka** [comment]
Hi @sarankup,
this module doesn't support Twitter. I muse see your implementation with GitHub. Please write me it here. I use OAuth2 module in 2 or 3 projects and everything is ok.

Thanks.

**Comment by sarankup** [comment]
Hi Petersirka,

SUPER FAST. THANK YOU.

Apologies. It is my mistake. In the callback I have mentioned twitter code I implemented. This is fixed now.
