### ISSUE TITLE
mail using sendgrid

### ISSUE THREAD

**Issue by sarankup** [totaljs/modules#35]
Hi,

I am hosting my application using Google Compute Engine, and it allow me to send email via SendGrid. Please refer the page at https://cloud.google.com/compute/docs/tutorials/sending-mail#nodejssendgrid

I like to use total.js own mail option which is working well for me now using google smtp.gmail.com. Could you please advise how to configure total.js/mail to work with SendGrid. SendGrid offer it own package at https://sendgrid.com/docs/Integrate/Code_Examples/nodejs.html.

But, still I prefer to use total.js/mail. Please advise.

**Comment by petersirka** [comment]
Hi @sarankup,
can you send me on __my e-mail__ some __test__ (user, password, etc.) credentials for SendGrid? I must test it in my computer.

Thanks.

**Comment by sarankup** [comment]
Hi Petersirka,

Thank you so much. I have sent my login credentials to petersirka@gmail.com
