### ISSUE TITLE
angular header creation

### ISSUE THREAD

**Issue by marcelsieber** [totaljs/modules#39]
Hallo Peter,

I was using angular.js with your module and I was wondering why I had allways "undefined" in the header of the outputfile. I think there is a little mistage in this line:
```javascript
self.repository['$head'] += angularBeg + angularEnd;
```
If I am not using ngStyle the variable self.repository['$head'] is undefined and it return "undefined" + angularBeg + angularEnd.
Replacing the line with
```javascript
self.repository['$head'] = (self.repository['$head'] || '') +  angularBeg + angularEnd;
```
solved the problem.

Thanks for all your work.

Edit:
Little Mistake on line 83:
```javascript
old: framework.helpers.call(self, arguments[i]);
new: framework.helpers.ngCommon.call(self, arguments[i]);
```

**Comment by petersirka** [comment]
Hi @marcelsieber,
many thanks. The bug has been fixed.

**Comment by marcelsieber** [comment]
Little Mistake on line 83:
```javascript
old: framework.helpers.call(self, arguments[i]);
new: framework.helpers.ngCommon.call(self, arguments[i]);
```
