### ISSUE TITLE
auth.js

### ISSUE THREAD

**Issue by KiPSOFT** [totaljs/modules#46]
Readme file example wrong in auth module.

auth.onAuthorization changed v2, auth.onAuthorize.

Peter my idea, more attention backward compatibility for security modules.

**Comment by petersirka** [comment]
Yes, you're right. I'll fix it.
__more attention__: I'll create blog about it.

Sorry and thanks, I cleaned :100:

**Comment by petersirka** [comment]
I have fixed it.
