### ISSUE TITLE
Stylus module "CONFIG(...).indexOf is not a function"

### ISSUE THREAD

**Issue by Creeplays** [totaljs/modules#62]
Getting that error:
```======= 2016-11-21 13:30:11: TypeError: CONFIG(...).indexOf is not a function TypeError: CONFIG(...).indexOf is not a function```
there:
https://github.com/totaljs/modules/blob/master/CSS/stylus/stylus.js#L10
Replacing with
```F.accept('.styl','text/css');```
Works fine.

**Comment by Creeplays** [comment]
Oh, not fine. It doesn't :D

**Comment by petersirka** [comment]
Hi @Creeplays, I have fixed it. Try it.
Thank you.

**Comment by Creeplays** [comment]
You are awesome! Thank you :D
