### ISSUE TITLE
the twitter module does not work

### ISSUE THREAD

**Issue by gyldcs** [totaljs/modules#69]
the example provided in the [twitter module](https://github.com/totaljs/modules/tree/master/Miscellaneous/twitter) returns an error:
> {"errors": [ {  "code": 215,  "message": "Bad Authentication data." } ] }

(also created an app in apps.twitter.com for the keys)

thanks

**Comment by petersirka** [comment]
I'll add a support into the OAuth 2.0 module in short time.
Thank you!

**Comment by ivanlunardi** [comment]
any news about tweeter support ?

**Comment by gyldcs** [comment]
@ivanlunardi I used an npm package insted
