### ISSUE TITLE
nosqlexplorer does not work as expected ... maybe I am wrong :-)

### ISSUE THREAD

**Issue by wiseflat** [totaljs/modules#70]
Hi Peter,

I try to use [nosqlexplorer](https://github.com/totaljs/modules/tree/master/Miscellaneous/nosqlexplorer) without success.

I set up my environnement as you said in the link above inside my adminmonitor project.
I tried this link : http://127.0.0.1:8000/$nosqlexplorer/?name=wt

Same result.. I cannot browse my nosqldatabase.

![capture d ecran 2017-05-31 a 19 38 57](https://cloud.githubusercontent.com/assets/7662169/26645590/d49175d0-4638-11e7-972c-05db56b1a999.png)

I really like this solution.
Can you tell me what to do ?

Cheers

**Comment by petersirka** [comment]
I have tested it and everything works correctly. I think that you don't have installed nosqlexplorer module correctly.

**Comment by wiseflat** [comment]
Hey Peter, thx for your answer
I didn't looked closely to your code...

Your documentation says : 
```
// Change URL to `nosqlexplorer` in a configuration file
nosqlexplorer-url          : /$nosqlexplorer/
```

But Line 4 [nosqlexplorer.js](https://github.com/totaljs/modules/blob/master/Miscellaneous/nosqlexplorer/nosqlexplorer.js)

```
URL = F.config['nosqlexporer-url'];
```
need to be
```
URL = F.config['nosqlexplorer-url'];
```

Now it's working. But I am redirect to your online nosqlexplorer. 
Can we use it offline ?

Regards

**Comment by petersirka** [comment]
Is your URL available from the internet? I think that you use localhost/127.0.0.1 and NoSQL explorer doesn't resolve your URL.

Thank you!

BTW: I'm going to fix the module (or you can create a pull request 👍)

**Comment by wiseflat** [comment]
Ok i will create a pull request. 
But can we use the explorer completely offline?

**Comment by petersirka** [comment]
Thank you! This is not possible. Maybe I can publish NoSQL explorer as open-source project.

**Comment by wiseflat** [comment]
Your framework is great ! And an open-source project should be a killer feature ! I hope it will happen soon.

I didn't really develop anything yet because your framework is a "turnkey solution", Otherwise I will have to develop my own module :-(

Think about it...
