### ISSUE TITLE
cnd.totaljs.com cdn down - 502 error

### ISSUE THREAD

**Issue by JohnRSim** [totaljs/modules#72]
https://cnd.totaljs.com/oauth2.js

Getting 502 nginx error accessing CDN

**Comment by MartinKolarik** [comment]
@petersirka not sure where this is hosted at the moment, but consider using [jsDelivr](https://www.jsdelivr.com). It can serve all packages from npm and releases from GitHub and provides the best uptime and perf you can get.

**Comment by petersirka** [comment]
@JohnRSim I have fixed it, the correct url is: https://cdn.totaljs.com/oauth2.js
@MartinKolarik I use [__Amazon CloudFront__](https://aws.amazon.com/cloudfront/pricing/), but good to know - thank you.
