### ISSUE TITLE
the pug module does not work

### ISSUE THREAD

**Issue by buckle2000** [totaljs/modules#73]
```node
======= 2017-10-04 23:27:18: default ---> TypeError: Cannot read property 'success' of undefined (http://localhost:8000/) TypeError: Cannot read property 'success' of undefined
    at Controller.view (eval at F.install (...\node_modules\total.js\index.js:3712:48), <anonymous>:65:19)
```
If I comment out this line in `pug.js`:
```node
self.subscribe.success();
```
The module works

**Comment by buckle2000** [comment]
Also, how to get tags like `@meta` work in pug?

**Comment by petersirka** [comment]
Hi @buckle2000,
just create a pull request with fix.

- `@meta` I don't know, I don't use pug.

100x thank you!

**Comment by buckle2000** [comment]
1. I mean the `@meta` in the original view engine
2. If I intstalled this module, I can no longer use html views.

**Comment by petersirka** [comment]
If you use `Pug` then Total.js view engine won't work. You need to choose: Pug or Total.js View Engine :-D ...  but you can create own inline compiler:

https://docs.totaljs.com/latest/en.html#pages~View%20engine~(defining-custom-3rd-compilers)
